name: task_manager
description:

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.15
  pin_code_fields: ^8.0.1



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0




flutter:

  uses-material-design: true

  assets:
   - assets/images/